# Generated by Django 3.2.6 on 2021-08-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('imageUrls', models.BooleanField(default=False)),
                ('minAge', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('sponsor', models.CharField(max_length=100)),
                ('schedule', models.BooleanField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
